---
extends:
- eslint:recommended
- plugin:import/errors
- plugin:import/warnings
parserOptions:
  ecmaVersion: 8
  ecmaFeatures:
    experimentalObjectRestSpread: true
env:
  node: true
settings:
  import/resolver: node
