image: node:alpine

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

before_script:
  - yarn

build:
  stage: build
  script:
    - yarn run build
  artifacts:
    paths:
      - dist/

lint:
  stage: test
  script:
    - yarn run lint

check format:
  stage: test
  script:
    - yarn run format:check
