image: node:alpine

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

before_script:
  - npm i

stages:
  - build
  - lint

typescript:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

eslint:
  stage: lint
  script:
    - npm run lint:eslint

prettier:
  stage: lint
  script:
    - npm run lint:prettier
