name: Node.js

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn
      - run: yarn run build
      - run: yarn run check:eslint
      - run: yarn run check:prettier
